apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    kubernetes.io/name: binddns
  name: binddns
  namespace: kube-system
spec:
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 9853
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 9853
  selector:
    app: binddns-controller
  sessionAffinity: None
  type: LoadBalancer
